export const citiesData = [
    {
      city_name: "Paris",
      country: "France",
      continent: "Europe",
      rating: 5,
      image: "https://ik.imagekit.io/wletmmv9huf/cities/parisL_X3_yTcZAj.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645796076951",
      image2: "https://ik.imagekit.io/wletmmv9huf/cities/paris_FKxm6sFpf.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645796076748",
      city_description: "Paris (nicknamed the 'City of light') is the capital city of France, and the largest city in France. The area is 105 square kilometres (41 square miles), and around 2.15 million people live there. The Seine river runs through the oldest part of Paris, and divides it into two parts, known as the Left Bank and the Right Bank. It is surrounded by many forests. Paris is also the center of French economy, politics, traffic and culture. Paris has many art museums and historical buildings. As a traffic center, Paris has a very good underground subway system (called the Metro). It also has two airports. The Metro was built in 1900, and its total length is more than 200 km (120 mi). The city has a multi-cultural style, because 19% of the people there are from outside France.[3] There are many different restaurants with all kinds of food.", 
      city_attractions: ["The Eiffel Tower", "The Louvre Museum", "Notre Dame Cathedral", "Sainte-Chapelle", "River Seine", "Les Catacombes"],
      great_for: ["families", "solo", "city break", "romance", "shopping"],
      tags: ["paris", "france", "eiffel tower", "city", "europe"],
      budget: "££",
      holiday_type:"city break"
  },
  {
    city_name: "Bangkok",
    country: "Thailand",
    continent: "Asia",
    rating: 4,
    image: "https://ik.imagekit.io/wletmmv9huf/cities/bangkok_KbuxJCNBW?ik-sdk-version=javascript-1.4.3&updatedAt=1645797282947",
    image2: "https://ik.imagekit.io/wletmmv9huf/cities/bangkok_XBr80SLvFj5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645797235636",
    city_description: "Bangkok, Thai Krung Thep, city, capital, and chief port of Thailand. It is the only cosmopolitan city in a country of small towns and villages and is Thailand’s cultural and commercial centre. Bangkok is located on the delta of the Chao Phraya River, about 25 miles (40 km) from the Gulf of Thailand. It was formerly divided into two municipalities—Krung Thep on the east bank and Thon Buri on the west—connected by several bridges. In 1971 the two were united as a city-province with a single municipal government. In 1972 the city and the two surrounding provinces were merged into one province, called Krung Thep Maha Nakhon (Bangkok Metropolis). The metropolis is a bustling, crowded city, with temples, factories, shops, and homes juxtaposed along its roads and canals. It is also a major tourist destination, noted for bountiful cultural attractions and a nightlife that includes a flourishing sex trade.", 
    city_attractions: ["Wat Phra Chetuphon", "Temple of Dawn", "Chatuchak Weekend Market", "Jim Thompson House", "Temple of the Emerald Buddha", "The Golden Mount", "Siam Paragon", "The Grand Palace"],
    great_for: ["solo", "backpacking", "adventure", "nightlife"],
    tags: ["bangkok", "thailand", "backpacking", "adventure", "city", "asia"],
    budget: "£",
    holiday_type:"adventure"
  },
  {
    city_name: "Cancun",
    country: "Mexico",
    continent: "South America",
    rating: 5,
    image: "https://ik.imagekit.io/wletmmv9huf/cities/cancunL_RvL0cc02i.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998477197",
    image2: "https://ik.imagekit.io/wletmmv9huf/cities/cancun_nDM44BINp.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998475832",
    city_description: "Cancun is recognized throughout the world for its spectacular white sand beaches and its fascinating sea in turquoise blue tones. With unique natural places, Mayan culture, water activities and adventure. International cuisine, spectacular golf courses, sophisticated spa facilities, exclusive shopping centers, typical handicraft markets as well as shows, bars and nightclubs that give fame to its incomparable nightlife.Cancun is recognized worldwide for its spectacular beaches of fine white sand, its fascinating turquoise blue sea and unparalleled weather, as well as excellent air and land connectivity, and a first-class hotel infrastructure that places it as one of the best destinations tourist in the world thanks to everything it offers to its visitors: Outdoor activities, adventure tourism, archeological sites, Mayan culture and history, a variety of gastronomic experiences, spectacular shopping centers, and seductive entertainment offers.", 
    city_attractions: ["Chichén Itzá","El Rey Maya Ruins","The Maya Museum","Cancun Underwater Museum","El Meco Archaeological Site","Scenic Tower", "Xcaret"],
    great_for: ["adventure", "nightlife", "family", "honeymoon", "sun"],
    tags: ["cancun", "mexico", "backpacking", "adventure", "city", "south america", "beach"],
    budget: "£££",
    holiday_type:"sun"
  },
  {
    city_name: "Bogota",
    country: "Colombia",
    continent: "South America",
    rating: 3,
    image: "https://ik.imagekit.io/wletmmv9huf/cities/bogotaL_gM9ewSGvU7L.png?ik-sdk-version=javascript-1.4.3&updatedAt=1645998480199",
    image2: "https://ik.imagekit.io/wletmmv9huf/cities/Bogota_98pNNC8NK.png?ik-sdk-version=javascript-1.4.3&updatedAt=1645998475541",
    city_description: "Bogota is the capital of Colombia. Located in the centre of the country at an altitude of approximately 2,600 metres, Bogotá enjoys an almost perfect climate with average temperatures varying from 9 to 23 degrees centigrade.The city has a population of around 8 million and is divided into a number of different areas including the historic centre 'La Candelaria', the downtown business district and several modern and prosperous suburbs. Getting around is relatively easy and inexpensive thanks to the city's innovative TransMilenio metro-bus service. There are too many things to do and see in the city to list here but among the highlights are the colonial style buildings of La Candelaria; the Gold Museum with its unique collection of pre-Colombian gold work; the view from the Monastery of Monserrate which overlooks the city and the Botanic gardens which is like a miniature national park. ", 
    city_attractions: ["Monserrate","Botero Museum","Plaza de Bolívar","Parque de la 93","Jardín Botánico de Bogotá José Celestino","Bogotá Museum of Modern Art MAMBO"],
    great_for: ["solo", "backpacking", "adventure", "nightlife"],
    tags: ["bogota", "colombia", "backpacking", "adventure", "city", "south america"],
    budget: "£",
    holiday_type:"adventure"
  },
  {
    city_name: "Florence",
    country: "Italy",
    continent: "Europe",
    rating: 3,
    image: "https://ik.imagekit.io/wletmmv9huf/cities/florenceL_t7H70tZKw.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998475408",
    image2: "https://ik.imagekit.io/wletmmv9huf/cities/florence_cAlZd1MoaC.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998474905",
    city_description: "Florence is a city in Central Italy and the capital city of the Tuscany region. It is the most populated city in Tuscany, with 383,084 inhabitants in 2013, and over 1,520,000 in its metropolitan area.The city attracts millions of tourists each year, and UNESCO declared the Historic Centre of Florence a World Heritage Site in 1982. The city is noted for its culture, Renaissance art and architecture and monuments.Florence originated as a Roman city, and later, after a long period as a flourishing trading and banking medieval commune, it was the birthplace of the Italian Renaissance. It was politically, economically, and culturally one of the most important cities in Europe and the world from the 14th to 16th centuries.Florence was home to the Medici, one of European history's most important noble families. Lorenzo de' Medici was considered a political and cultural mastermind of Italy in the late 15th century. Two members of the family were popes in the early 16th century: Leo X and Clement VII. Catherine de Medici married King Henry II of France and, after his death in 1559, reigned as regent in France. Marie de' Medici married Henry IV of France and gave birth to the future King Louis XIII. The Medici reigned as Grand Dukes of Tuscany, starting with Cosimo I de' Medici in 1569 and ending with the death of Gian Gastone de' Medici in 1737.", 
    city_attractions: ["Florence Cathedral (the Duomo)", "Giotto's Campanile", "Palazzo Vecchio","Leonardo Da Vinci Museum", "Uffizi Palace and Gallery", "Galleria dell'Accademia (home to Statue of David)" ],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["florence", "italy", "backpacking", "adventure", "city", "europe"],
    budget: "£££",
    holiday_type:"city break"
  },
  {
    city_name: "Brussels",
    country: "Belgium",
    continent: "Europe",
    rating: 4,
    image: "https://ik.imagekit.io/wletmmv9huf/cities/brusselsL_Iiz44RG_u.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998475425",
    image2: "https://ik.imagekit.io/wletmmv9huf/cities/brussels_wMwQGGc8ot.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998474142",
    city_description: "Unassuming Brussels is the capital of Belgium, Flanders and Europe. Medieval Grand-Place is indeed grand, with many 17th-century buildings and daily flower markets. Reopened in 2006, the Atomium, Brussels' Eiffel Tower, provides great views, both inside and out. Architecture fans should visit the MusÃ©e Horta, home of Belgian master architect Victor Horta. St Gery's clubs and bars are packed all year round. Seafood eateries abound in Ste Catherine. Exploring the narrow streets on foot is more fun than getting snarled up in traffic.", 
    city_attractions: [ "Grand Place", "Musee des Beaux-Arts d'Ixelles", "Musee Constantin Meunier", "Train World", "Luxembourg Square"],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["brussels", "belgium", "backpacking", "adventure", "city", "europe"],
    budget: "££",
    holiday_type:"city break"
  },
  {
    city_name: "Zurich",
    country: "Switzerland",
    continent: "Europe",
    rating: 4,
    image: "https://ik.imagekit.io/wletmmv9huf/cities/zurichL_aIyljayN6.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998474753",
    image2: "https://ik.imagekit.io/wletmmv9huf/cities/zurich_qee0pEGCc.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998473621",
    city_description: "Zürich is the largest city in Switzerland and the capital of the canton of Zürich. It is located in north-central Switzerland. Permanently settled for over 2,000 years, Zürich was founded by the Romans, who, in 15 BC, called it Turicum. However, early settlements have been found dating back more than 6,400 years (although this only indicates human presence in the area and not the presence of a town that early).The official language of Zürich is German,but the main spoken language is Zürich German, the local variant of the Alemannic Swiss German dialect.Zürich is among the world's largest financial centres despite having a relatively small population.The city is home to many financial institutions and banking companies. ", 
    city_attractions: [ "Swiss National Museum","Kunsthaus","Schauspielhaus Zürich","Lake Zurich"],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["zurich", "switzerland", "backpacking", "adventure", "city", "europe"],
    budget: "£££",
    holiday_type:"adventure"
  },
  {
    city_name: "Dublin",
    country: "Ireland",
    continent: "Europe",
    rating: 3,
    image: "https://ik.imagekit.io/wletmmv9huf/cities/dublinL_CDsxJAqb1.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998474067",
    image2: "https://ik.imagekit.io/wletmmv9huf/cities/dublin_8Sq-CdlfVSS.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998473256",
    city_description: "Dublin is the capital and largest city of Ireland.Situated on a bay on the east coast, at the mouth of the River Liffey, it lies within the province of Leinster. It is bordered on the south by the Dublin Mountains, a part of the Wicklow Mountains range.The area of Dublin Bay has been inhabited by humans since prehistoric times, fish traps discovered from excavations during the construction of the Convention Centre Dublin indicate human habitation as far back as 6,000 years ago while further traps were also discovered closer to the old settlement of the city of Dublin on the south quays near St. James's Gate which also indicate mesolithic human activity.", 
    city_attractions: [ "The Guinness Storehouse","St Patrick's and Christ Church Cathedrals","Dublin Castle","Kilmainham Gaol"],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["dublin", "ireland", "backpacking", "adventure", "city", "europe"],
    budget: "£",
    holiday_type:"city break"
  },
  {
    city_name: "Jakarta",
    country: "Indonesia",
    continent: "Asia",
    rating: 2,
    image: "https://ik.imagekit.io/wletmmv9huf/cities/jakartaL_W2RdwHNuk.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998473779",
    image2: "https://ik.imagekit.io/wletmmv9huf/cities/jakarta_duHHu5TgL.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998473019",
    city_description: "Jakarta is the largest city in Southeast Asia and serves as the diplomatic capital of ASEAN. The city is the centre of the economy, culture, and politics of Indonesia. It has a province level status which has a population of 10,562,088 as of 2020.Jakarta is one of the oldest continuously inhabited cities in Southeast Asia. Established in the fourth century as Sunda Kelapa, the city became an important trading port for the Sunda Kingdom.", 
    city_attractions: [ "National Monument","Taman Mini Indonesia Indah","Istiqlal Mosque","Taman Impian Jaya Ancol"],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["jakarta", "indonesia", "backpacking", "adventure", "city", "asia"],
    budget: "£",
    holiday_type:"adventure"
  },
  {
    city_name: "Lima",
    country: "Peru",
    continent: "South America",
    rating: 5,
    image: "https://ik.imagekit.io/wletmmv9huf/cities/limaL_ZmGY8nkU8.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998473772",
    image2: "https://ik.imagekit.io/wletmmv9huf/cities/lima_xOTJLyFcF.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645998472898",
    city_description: "Lima is the capital and the largest city of Peru. It is located in the valleys of the Chillón, Rímac and Lurín Rivers, in the desert zone of the central coastal part of the country, overlooking the Pacific Ocean. Together with the seaport of Callao, it forms a contiguous urban area known as the Lima Metropolitan Area. With a population of more than 9.7 million and more than 10.7 million in its metropolitan area,[4] Lima is one of the largest cities in the Americas.", 
    city_attractions: ["Larco Museum","Huaca Pucllana","Basílica y Convento de San Francisco de Lima","Cathedral of Lima"],
    great_for: ["solo", "backpacking", "city break" ],
    tags: ["lima", "peru", "backpacking", "adventure", "city", "south america"],
    budget: "£",
    holiday_type:"adventure"
  },
  {
    city_name: "Marseille",
    country: "France",
    continent: "Europe",
    rating: 4,
    image: "",
    image2: "",
    city_description:
      "Marseille is the  'oldest city in France' and indeed one of the oldest in western Europe. The city was founded as Massalia in around 600 BC, and soon developed into an important port in the ancient Greek world. For the Greeks, and later for the Romans, it was a major point of transition and trade between the civilisations of the Mediterranean, and those of Gaul and northwest Europe. For a day-trip or a weekend break or short stay, Marseilles is an ideal destination, specially during those times of the year when it tends to be bathed in Mediterranean sunshine while much of France further north is still struggling with spring or  dampened by autumn mists and showers. And getting to the tourist quarter of Marseille around the Old Port is remarkably easy.",
    city_attractions: [
      "The Mucem",
      "The Fort Saint Jean",
      "The Eglise Saint Laurent",
      "La Major cathedral",
      "La Canebière",
      "Le Musée Cantini",
    ],
    great_for: ["families", "solo", "sun", "romance", "adventure"],
    tags: ["marseille", "france", "city", "europe"],
    budget: "££",
    holiday_type: "city break",
  },
  {
    city_name: "Lyon",
    country: "France",
    continent: "Europe",
    rating: 4,
    image: "",
    image2: "",
    city_description:
      "Lyon is France's second city, one of France's oldest cities, and is reputed as the gourmet capital of France. It's large historic centre, Le Vieux Lyon, is a UNESCO World Heritage site, and is the largest ensemble of Renaissance buildings in Europe. In addition, Lyon also has a new museum which looks as if it may vie for celebrity with the Guggenheim museum in Bilbao. The new Confluences museum lies at the point where the Saône and Rhone rivers meet, and is a museum of science and anthropology, with plenty of interactive exhibits. The confluence of these two great rivers is the hub of an urban area with over two million inhabitants. Lyon is also the main city on the road and rail routes between Paris and the south of France, Paris and the Alps and Italy, and northern Europe and Spain.",
    city_attractions: [
      "Place Bellecour",
      "Notre Dame de Fourvière",
      "Cathedral Saint Jean",
      "Lyon fine arts museum",
      "Festival of Lights",
      "Nuits de Fourvière",
    ],
    great_for: ["solo", "romance", "adventure", "sun", "shopping"],
    tags: ["lyon", "adventure", "city", "europe"],
    budget: "£",
    holiday_type: "city break",
  },
{
    city_name: "Chiang Mai",
    country: "Thailand",
    continent: "Asia",
    rating: 4,
    image: "",
    image2: "",
    city_description:
      "Chiang Mai, also spelled Chiengmai, largest city in northern Thailand and the third largest city in the nation after metropolitan Bangkok and Nakhon Ratchasima. It serves as the religious, economic, cultural, educational, and transportation centre for both northern Thailand and part of neighbouring Myanmar (Burma). Once the capital of an independent kingdom, the city also has strong cultural ties with Laos. Chiang Mai is a land of misty mountains and colourful hill tribes, a playground for seasoned travellers and a delight for adventurers. On a trip to this tranquil city, curious travellers can expand their horizons with Thai massage and cooking courses. Others will be bowled over by the variety of handicrafts and antiques. There are plenty of lively nightlife spots and excellent eateries specialising in local cuisine.",
    city_attractions: [
      "Wat Phra That Doi Suthep",
      "Doi Pui Village",
      "Doi Inthanon",
      "Wat Chedi Luang",
      "Wat Prasingh",
      "Chiang Mai Gate Market",
      "Highland People Discovery Museum",
      "Bua Thong Sticky Waterfalls"
    ],
    great_for: ["solo", "backpacking", "adventure", "nightlife"],
    tags: [
      "chiang mai",
      "thailand",
      "backpacking",
      "adventure",
      "city",
      "asia",
    ],
    budget: "£",
    holiday_type: "adventure",
  },

  ];