export const citiesData = [
    {
      city_name: "Paris",
      country: "France",
      continent: "Europe",
      rating: 5,
      image: "link",
      city_description: "Paris (nicknamed the 'City of light') is the capital city of France, and the largest city in France. The area is 105 square kilometres (41 square miles), and around 2.15 million people live there. The Seine river runs through the oldest part of Paris, and divides it into two parts, known as the Left Bank and the Right Bank. It is surrounded by many forests. Paris is also the center of French economy, politics, traffic and culture. Paris has many art museums and historical buildings. As a traffic center, Paris has a very good underground subway system (called the Metro). It also has two airports. The Metro was built in 1900, and its total length is more than 200 km (120 mi). The city has a multi-cultural style, because 19% of the people there are from outside France.[3] There are many different restaurants with all kinds of food.", 
      city_attractions: ["The Eiffel Tower", "The Louvre Museum", "Notre Dame Cathedral", "Sainte-Chapelle", "River Seine", "Les Catacombes"],
      great_for: ["families", "solo", "city break", "romance", "shopping"],
      tags: ["paris", "france", "eiffel tower", "city", "europe"],
      budget: "££",
      holiday_type:"city break"

  },
  {
    city_name: "Bangkok",
    country: "Thailand",
    continent: "Asia",
    rating: 4,
    image: "Link",
    city_description: "Bangkok, Thai Krung Thep, city, capital, and chief port of Thailand. It is the only cosmopolitan city in a country of small towns and villages and is Thailand’s cultural and commercial centre. Bangkok is located on the delta of the Chao Phraya River, about 25 miles (40 km) from the Gulf of Thailand. It was formerly divided into two municipalities—Krung Thep on the east bank and Thon Buri on the west—connected by several bridges. In 1971 the two were united as a city-province with a single municipal government. In 1972 the city and the two surrounding provinces were merged into one province, called Krung Thep Maha Nakhon (Bangkok Metropolis). The metropolis is a bustling, crowded city, with temples, factories, shops, and homes juxtaposed along its roads and canals. It is also a major tourist destination, noted for bountiful cultural attractions and a nightlife that includes a flourishing sex trade.", 
    city_attractions: ["Wat Phra Chetuphon", "Temple of Dawn", "Chatuchak Weekend Market", "Jim Thompson House", "Temple of the Emerald Buddha", "The Golden Mount", "Siam Paragon", "The Grand Palace"],
    great_for: ["solo", "backpacking", "adventure", "nightlife"],
    tags: ["bangkok", "thailand", "backpacking", "adventure", "city", "asia"],
    budget: "£",
    holiday_type:"adventure"
  },
  {
    city_name: "Cancún",
    country: "Mexico",
    continent: "South America",
    rating: 4,
    image: "Link",
    city_description: "Cancun is recognized throughout the world for its spectacular white sand beaches and its fascinating sea in turquoise blue tones. With unique natural places, Mayan culture, water activities and adventure. International cuisine, spectacular golf courses, sophisticated spa facilities, exclusive shopping centers, typical handicraft markets as well as shows, bars and nightclubs that give fame to its incomparable nightlife.Cancun is recognized worldwide for its spectacular beaches of fine white sand, its fascinating turquoise blue sea and unparalleled weather, as well as excellent air and land connectivity, and a first-class hotel infrastructure that places it as one of the best destinations tourist in the world thanks to everything it offers to its visitors: Outdoor activities, adventure tourism, archeological sites, Mayan culture and history, a variety of gastronomic experiences, spectacular shopping centers, and seductive entertainment offers.", 
    city_attractions: ["Palapas dotting a white-sand beach in Cancun", "Mayan Ruins of Chichén Itzá","El Rey Maya Ruins","The Maya Museum","Cancun Underwater Museum","El Meco Archaeological Site","Scenic Tower & Xcaret"],
    great_for: ["solo", "backpacking", "adventure", "nightlife"],
    tags: ["cancun", "mexico", "backpacking", "adventure", "city", "south america"],
    budget: "£",
    holiday_type:"adventure"
  },
  {
    city_name: "Bogota",
    country: "Colombia",
    continent: "South America",
    rating: 4,
    image: "Link",
    city_description: "Bogota is the capital of Colombia. Located in the centre of the country at an altitude of approximately 2,600 metres, Bogotá enjoys an almost perfect climate with average temperatures varying from 9 to 23 degrees centigrade.The city has a population of around 8 million and is divided into a number of different areas including the historic centre 'La Candelaria', the downtown business district and several modern and prosperous suburbs. Getting around is relatively easy and inexpensive thanks to the city's innovative TransMilenio metro-bus service. There are too many things to do and see in the city to list here but among the highlights are the colonial style buildings of La Candelaria; the Gold Museum with its unique collection of pre-Colombian gold work; the view from the Monastery of Monserrate which overlooks the city and the Botanic gardens which is like a miniature national park. ", 
    city_attractions: ["Monserrate","Botero Museum","Plaza de Bolívar","Parque de la 93","Jardín Botánico de Bogotá José Celestino","Bogotá Museum of Modern Art MAMBO"],
    great_for: ["solo", "backpacking", "adventure", "nightlife"],
    tags: ["bogota", "colombia", "backpacking", "adventure", "city", "south america"],
    budget: "£",
    holiday_type:"adventure"
  },
  {
    city_name: "Firenze",
    country: "Italy",
    continent: "Europe",
    rating: 4,
    image: "Link",
    city_description: "Florence is a city in Central Italy and the capital city of the Tuscany region. It is the most populated city in Tuscany, with 383,084 inhabitants in 2013, and over 1,520,000 in its metropolitan area.The city attracts millions of tourists each year, and UNESCO declared the Historic Centre of Florence a World Heritage Site in 1982. The city is noted for its culture, Renaissance art and architecture and monuments.Florence originated as a Roman city, and later, after a long period as a flourishing trading and banking medieval commune, it was the birthplace of the Italian Renaissance. It was politically, economically, and culturally one of the most important cities in Europe and the world from the 14th to 16th centuries.Florence was home to the Medici, one of European history's most important noble families. Lorenzo de' Medici was considered a political and cultural mastermind of Italy in the late 15th century. Two members of the family were popes in the early 16th century: Leo X and Clement VII. Catherine de Medici married King Henry II of France and, after his death in 1559, reigned as regent in France. Marie de' Medici married Henry IV of France and gave birth to the future King Louis XIII. The Medici reigned as Grand Dukes of Tuscany, starting with Cosimo I de' Medici in 1569 and ending with the death of Gian Gastone de' Medici in 1737.", 
    city_attractions: ["Florence Cathedral (the Duomo)", "Giotto’s Campanile", "Palazzo Vecchio","Leonardo Da Vinci Museum", "Uffizi Palace and Gallery", "Galleria dell’Accademia (home to Statue of David)" ],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["florence", "italy", "backpacking", "adventure", "city", "europe"],
    budget: "£££",
    holiday_type:"adventure"
  },
  {
    city_name: "Bruxelles",
    country: "Belgium",
    continent: "Europe",
    rating: 4,
    image: "Link",
    city_description: "Bruxelles is a region of Belgium comprising 19 municipalities, including the City of Brussels, which is the capital of Belgium. Brussels grew from a small rural settlement on the river Senne to become an important city-region in Europe. Since the end of the Second World War, it has been a major centre for international politics and home to numerous international organisations, politicians, diplomats and civil servants. The secretariat of the Benelux and the headquarters of NATO are also located in Brussels.The Brussels Metro is the only rapid transit system in Belgium. In addition, both its airport and railway stations are the largest and busiest in the country.", 
    city_attractions: [ "Grand Place", "Manneken Pis", "Atomium","La Monnaie/De Munt","Museums of Art and History"],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["bruxelles", "belgium", "backpacking", "adventure", "city", "europe"],
    budget: "£££",
    holiday_type:"adventure"
  },
  {
    city_name: "Zürich",
    country: "Switzerland",
    continent: "Europe",
    rating: 4,
    image: "Link",
    city_description: "Zürich is the largest city in Switzerland and the capital of the canton of Zürich. It is located in north-central Switzerland. Permanently settled for over 2,000 years, Zürich was founded by the Romans, who, in 15 BC, called it Turicum. However, early settlements have been found dating back more than 6,400 years (although this only indicates human presence in the area and not the presence of a town that early).The official language of Zürich is German,but the main spoken language is Zürich German, the local variant of the Alemannic Swiss German dialect.Zürich is among the world's largest financial centres despite having a relatively small population.The city is home to many financial institutions and banking companies. ", 
    city_attractions: [ "Swiss National Museum","Kunsthaus","Schauspielhaus Zürich","Lake Zurich"],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["zürich", "switzerland", "backpacking", "adventure", "city", "europe"],
    budget: "£££",
    holiday_type:"adventure"
  },
  {
    city_name: "Dublin",
    country: "Ireland",
    continent: "Europe",
    rating: 4,
    image: "Link",
    city_description: "Dublin is the capital and largest city of Ireland.Situated on a bay on the east coast, at the mouth of the River Liffey, it lies within the province of Leinster. It is bordered on the south by the Dublin Mountains, a part of the Wicklow Mountains range.The area of Dublin Bay has been inhabited by humans since prehistoric times, fish traps discovered from excavations during the construction of the Convention Centre Dublin indicate human habitation as far back as 6,000 years ago while further traps were also discovered closer to the old settlement of the city of Dublin on the south quays near St. James's Gate which also indicate mesolithic human activity.", 
    city_attractions: [ "The Guinness Storehouse","St Patrick's and Christ Church Cathedrals","Dublin Castle","Kilmainham Gaol"],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["dublin", "ireland", "backpacking", "adventure", "city", "europe"],
    budget: "££",
    holiday_type:"adventure"
  },
  {
    city_name: "Jakarta",
    country: "Indonesia",
    continent: "Europe",
    rating: 4,
    image: "Link",
    city_description: "Jakarta is the largest city in Southeast Asia and serves as the diplomatic capital of ASEAN. The city is the centre of the economy, culture, and politics of Indonesia. It has a province level status which has a population of 10,562,088 as of 2020.Jakarta is one of the oldest continuously inhabited cities in Southeast Asia. Established in the fourth century as Sunda Kelapa, the city became an important trading port for the Sunda Kingdom.", 
    city_attractions: [ "National Monument","Taman Mini Indonesia Indah","Istiqlal Mosque","Taman Impian Jaya Ancol"],
    great_for: ["families", "solo", "city break", "romance", "shopping"],
    tags: ["jakarta", "indonesia", "backpacking", "adventure", "city", "asia"],
    budget: "££",
    holiday_type:"adventure"
  },
  {
    city_name: "Lima",
    country: "Peru",
    continent: "South America",
    rating: 4,
    image: "Link",
    city_description: "Lima is the capital and the largest city of Peru. It is located in the valleys of the Chillón, Rímac and Lurín Rivers, in the desert zone of the central coastal part of the country, overlooking the Pacific Ocean. Together with the seaport of Callao, it forms a contiguous urban area known as the Lima Metropolitan Area. With a population of more than 9.7 million and more than 10.7 million in its metropolitan area,[4] Lima is one of the largest cities in the Americas.", 
    city_attractions: ["Larco Museum","Huaca Pucllana","Basílica y Convento de San Francisco de Lima","Cathedral of Lima"],
    great_for: ["families", "solo", "city break", ],
    tags: ["lima", "peru", "backpacking", "adventure", "city", "south america"],
    budget: "£",
    holiday_type:"adventure"
  },
  ];