export const countriesData = [
    {
      country: "France",
      continent: "Europe",
      image: "https://ik.imagekit.io/wletmmv9huf/countries/franceL_1AjCbtgId.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1645798679129",
      image2: "https://ik.imagekit.io/wletmmv9huf/countries/franceS_aci3q709M.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646062048855",
      country_description: "France, the largest country in Western Europe, has long been a gateway between the continent's northern and southern regions. ... The sprawling, forested plateau of the Massif Central, a range of ancient mountains and extinct volcanoes, occupies France's southern interior.",
      cities: ["Paris", "Marseille", "Lyon"],
  },
  {
    country: "Thailand",
    continent: "Asia",
    image: "https://ik.imagekit.io/wletmmv9huf/countries/thailandL_QDbcM5w3S.png?ik-sdk-version=javascript-1.4.3&updatedAt=1645798252304",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/thailandS_jI7faN5ab.png?ik-sdk-version=javascript-1.4.3&updatedAt=1646062049279",
    country_description: "Thailand is in the heart of Southeast Asia. Cambodia and Laos border the country to the east and northeast, and Myanmar lies to the northwest. To the west is the Andaman Sea and the Gulf of Thailand, southeast of Burma. The long southern region, connecting with Malaysia, is hilly and forested. The highest mountains are in northern Thailand.",
    cities: ["Bangkok", "Chiang Mai"],
  },
  {
    country: "Indonesia",
    continent: "Asia",
    image: "https://ik.imagekit.io/wletmmv9huf/countries/indonesiaL_ei-GFX2hm8Q.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646000836628",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/indonesiaS_7XhQOkcrO.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646062048212",
    country_description: "Indonesia is a country in Southeast Asia and Melanesia between the Indian and Pacific oceans. It consists of over 17,000 islands, including Sumatra, Sulawesi, Java, and parts of Borneo and New Guinea. Indonesia is the world's largest island country and the 14th-largest country by area, at 1,904,569 square kilometres (735,358 square miles).",
    cities: ["Jakarta", "Surabaya"],
  },
  {
    country: "Madagascar",
    continent: "Africa",
    image: "https://ik.imagekit.io/wletmmv9huf/countries/madagascarL_TtqxvrvMs.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646000836887",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/madagascarS_ajrIri7HL.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646062048103",
    country_description: "Madagascar, previously known as the Malagasy Republic, is an island country in the Indian Ocean, approximately 400 kilometres (250 miles) off the coast of East Africa across the Mozambique Channel. At 592,800 square kilometres (228,900 sq mi) Madagascar is the world's second-largest island country, after Indonesia.",
    cities: ["Antananarivo", "Antsirabe"],
  },
  {
    country: "Peru",
    continent: "South America",
    image: "https://ik.imagekit.io/wletmmv9huf/countries/peruL_6nbfHiK29.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646000836897",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/peruS_fzKNYIa0u.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646062047620",
    country_description: "Peru is a megadiverse country with habitats ranging from the arid plains of the Pacific coastal region in the west to the peaks of the Andes mountains extending from the north to the southeast of the country to the tropical Amazon Basin rainforest in the east with the Amazon river.",
    cities: ["Lima", "Arequipa"],
  },
  {
    country: "Mexico",
    continent: "South America",
    image: "lihttps://ik.imagekit.io/wletmmv9huf/countries/mexicoL_KpWlCcVCOhCo.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646000836760nk",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/mexicoS_sF9PMlQCy.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646062047554",
    country_description: "With 26 UNESCO-declared world heritage sites, charming colonial towns and dozens of thrilling cities, there's plenty to explore in this country of 109 million. Outside the cities, stunning Pacific beaches, stark deserts, mangrove swamps and swimming holes provide all you need for a relaxing, romantic or adventurous vacation. Captivating, cosmopolitan and chaotic Mexico City and the 32 states offer an incredible abundance of experiences, from laid-back and leisurely to upbeat to adrenalin-charging.",
    cities: ["Mexico", "Guadalajara", "Cancun"],
  },
  {
    country: "Colombia",
    continent: "South America",
    image: "https://ik.imagekit.io/wletmmv9huf/countries/colombiaL_OOrtWrEL3u.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646000837105",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/colombiaS_EhhLjZvIH.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646062047305",
    country_description: "Colombia has major attractions for a tourist destination, such as Cartagena and its historic surroundings, which are on the UNESCO World Heritage List; the insular department of San Andrés, Providencia y Santa Catalina; and Santa Marta and the surrounding area. The coffee region is also a very popular destination, especially the traditional town of Salento, Quindío and its surroundings. Fairly recently, Bogotá, the nation's capital, has become Colombia's major tourist destination because of its improved museums and entertainment facilities and its major urban renovations, including the rehabilitation of public areas, the development of parks, and the creation of an extensive network of cycling routes. With its very rich and varied geography, which includes the Amazon and Andean regions, the Llanos, the Caribbean and Pacific coasts, and the deserts of La Guajira and Tatacoa Desert, and its unique biodiversity, Colombia also has major potential for ecotourism.",
    cities: ["Bogota", "Medellin", "Cartagena"],
  },
  {
    country: "Italy",
    continent: "Europe",
    image: "https://ik.imagekit.io/wletmmv9huf/countries/italyL_HLdT5ID4qb.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646000837016",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/italyS_8BuR_ikL-TZ.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646062047272",
    country_description: "From the silvery crests of the Alps to the sparkling Mediterranean Sea, Italy’s beauty is unparallelled. A visit could mean marveling at the Colosseum after a tender plate of pasta, or drifting lazily down a canal, your belly full of local Sangiovese. Explore Tuscan vineyards and olive groves or drool over boutiques in fashionable Milan. Look for mermaids from the cliffs of Sorrento or nibble on Parma’s famous cheese and prosciutto. Anywhere you choose, the country will captivate you.",
    cities: ["Rome", "Venice", "Florence", "Naples"],
  },
  {
    country: "Belgium",
    continent: "Europe",
    image: "https://ik.imagekit.io/wletmmv9huf/countries/belgiumL_FwQrMU6rvMO.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646000835863",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/belgiumS_Ugx3U5BlH.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646062047110",
    country_description: "From canal-laced, fairy-tale cities like Bruges and Ghent to the urban centres of Antwerp and Brussels, Belgium sits at the crossroads of medieval and modern Europe. The chance to sample famous exports such as chocolate and beer straight from the source only sweetens a visit.",
    cities: ["Brussels", "Bruges", "Antwerp"],
  },
  {
    country: "Switzerland",
    continent: "Europe",
    image: "https://ik.imagekit.io/wletmmv9huf/countries/switzerlandL_gFQDh8Lwz.png?ik-sdk-version=javascript-1.4.3&updatedAt=1646000838288",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/switzerlandS_lVUtGTijn.png?ik-sdk-version=javascript-1.4.3&updatedAt=1646062047798",
    country_description: "Tiny, multilingual Switzerland packs a lot into its landlocked borders: glittering lakes, sky-high peaks, postcard-perfect villages, world-class museums. Get a taste of it all with the Grand Tour, a 1,000-mile route that takes you to the medieval old city of Bern, towering Jungfraujoch, the iconic Matterhorn, and 42 other must-sees. Or choose your own fondue-fuelled adventure: Ski bunnies and adrenaline junkies can hit the slopes at Graubünden or Verbier; urban explorers can sample Zurich's burgeoning food scene or take in art at Basel's Kunstmuseum. Or just sit back, relax, and breathe in the fresh alpine air at one of Switzerland's luxurious spa resorts.",
    cities: ["Zurich", "Basel", "Geneva"],
  },
  {
    country: "Ireland",
    continent: "Europe",
    image: "https://ik.imagekit.io/wletmmv9huf/countries/irelandL_M2n6a3fD3.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646000832081",
    image2: "https://ik.imagekit.io/wletmmv9huf/countries/irelandS_Pjy63q_SH.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1646062047052",
    country_description: "Woven with wild greenery and Gaelic legends, the Emerald Isle is one of Europe’s most prized jewels. Rugged Atlantic beaches and mystery-shrouded sites rub shoulders with the cosmopolitan cities of Belfast and Dublin, where literary history and warm Irish hospitality are always in abundance.",
    cities: ["Dublin", "Cork", "Galway", "Limerick"],
  },

  ];